# Server Port
server.port=8080

# Disable database auto configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Avoid Hibernate issues
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false