# Server Port
server.port=8080

# Disable database auto configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Avoid Hibernate issues
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Multi-part file upload configuration
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.location=/tmp